// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"
)

const createRole = `-- name: CreateRole :one
INSERT INTO role (name, description) VALUES ($1, $2) RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createTokenBlacklist = `-- name: CreateTokenBlacklist :one
INSERT INTO token_blacklist (token) VALUES ($1) RETURNING id, token, created_at
`

func (q *Queries) CreateTokenBlacklist(ctx context.Context, token string) (TokenBlacklist, error) {
	row := q.db.QueryRowContext(ctx, createTokenBlacklist, token)
	var i TokenBlacklist
	err := row.Scan(&i.ID, &i.Token, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, last_names, email, username, password, status, birth_date, address, phone, role_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateUserParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	RoleID    string    `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.LastNames,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Status,
		arg.BirthDate,
		arg.Address,
		arg.Phone,
		arg.RoleID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET status = 'deleted' WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findRoleById = `-- name: FindRoleById :one
SELECT id, name, description FROM role WHERE id = $1
`

func (q *Queries) FindRoleById(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleById, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findRoleByName = `-- name: FindRoleByName :one
SELECT id, name, description FROM role WHERE name = $1
`

func (q *Queries) FindRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findTokenBlacklist = `-- name: FindTokenBlacklist :one
SELECT token FROM token_blacklist WHERE token = $1
`

func (q *Queries) FindTokenBlacklist(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, findTokenBlacklist, token)
	err := row.Scan(&token)
	return token, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT users.id, users.name, users.last_names, users.email, users.username, users.password, users.status, users.birth_date, users.address, users.phone, r.name as role
FROM users
INNER JOIN role r ON users.role_id = r.id
WHERE users.email = $1
`

type FindUserByEmailRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	Role      string    `json:"role"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.Role,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT users.id, users.name, users.last_names, users.email, users.username, users.status, users.birth_date, users.address, users.phone, r.name as role
FROM users
INNER JOIN role r ON users.role_id = r.id
WHERE users.id = $1
`

type FindUserByIdRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	Role      string    `json:"role"`
}

func (q *Queries) FindUserById(ctx context.Context, id string) (FindUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i FindUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.Role,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT users.id, users.name, users.last_names, users.email, users.username, users.password, users.status, users.birth_date, users.address, users.phone, r.name as role
FROM users
INNER JOIN role r ON users.role_id = r.id
WHERE users.username = $1
`

type FindUserByUsernameRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	Role      string    `json:"role"`
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.Role,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description FROM role
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT users.id, users.name, users.last_names, users.email, users.username, users.status, users.birth_date, users.address, users.phone, r.name as role
FROM users
INNER JOIN role r ON users.role_id = r.id
WHERE users.status = 'active'
`

type ListUsersRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	Role      string    `json:"role"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastNames,
			&i.Email,
			&i.Username,
			&i.Status,
			&i.BirthDate,
			&i.Address,
			&i.Phone,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, last_names = $2, username = $3
WHERE id = $4
RETURNING id
`

type UpdateUserParams struct {
	Name      string `json:"name"`
	LastNames string `json:"last_names"`
	Username  string `json:"username"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.LastNames,
		arg.Username,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
