// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"
)

const createRole = `-- name: CreateRole :one
INSERT INTO role (name, description) VALUES (?, ?) RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createTokenBlacklist = `-- name: CreateTokenBlacklist :one
INSERT INTO token_blacklist (token) VALUES (?) RETURNING id, token, created_at
`

func (q *Queries) CreateTokenBlacklist(ctx context.Context, token string) (TokenBlacklist, error) {
	row := q.db.QueryRowContext(ctx, createTokenBlacklist, token)
	var i TokenBlacklist
	err := row.Scan(&i.ID, &i.Token, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (id, name, last_names, email, username, password, status, birth_date, address, phone, role_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, name, last_names, email, username, password, status, birth_date, address, phone, created_at, role_id
`

type CreateUserParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	RoleID    string    `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.LastNames,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Status,
		arg.BirthDate,
		arg.Address,
		arg.Phone,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE user SET status = 'deleted' WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findRoleById = `-- name: FindRoleById :one
SELECT id, name, description FROM role WHERE id = ?
`

func (q *Queries) FindRoleById(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleById, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findRoleByName = `-- name: FindRoleByName :one
SELECT id, name, description FROM role WHERE name = ?
`

func (q *Queries) FindRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findTokenBlacklist = `-- name: FindTokenBlacklist :one
SELECT id, token, created_at FROM token_blacklist WHERE token = ?
`

func (q *Queries) FindTokenBlacklist(ctx context.Context, token string) (TokenBlacklist, error) {
	row := q.db.QueryRowContext(ctx, findTokenBlacklist, token)
	var i TokenBlacklist
	err := row.Scan(&i.ID, &i.Token, &i.CreatedAt)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, last_names, email, username, password, status, birth_date, address, phone, created_at, role_id FROM user WHERE email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, name, last_names, email, username, password, status, birth_date, address, phone, created_at, role_id FROM user WHERE id = ?
`

func (q *Queries) FindUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description FROM role
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, last_names, email, username, password, status, birth_date, address, phone, created_at, role_id FROM user
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastNames,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Status,
			&i.BirthDate,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE user SET name = ?, last_names = ?, email = ?, username = ?, password = ?, status = ?, birth_date = ?, address = ?, phone = ?, role_id = ? WHERE id = ? RETURNING id, name, last_names, email, username, password, status, birth_date, address, phone, created_at, role_id
`

type UpdateUserParams struct {
	Name      string    `json:"name"`
	LastNames string    `json:"last_names"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	BirthDate time.Time `json:"birth_date"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	RoleID    string    `json:"role_id"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.LastNames,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Status,
		arg.BirthDate,
		arg.Address,
		arg.Phone,
		arg.RoleID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastNames,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.BirthDate,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.RoleID,
	)
	return i, err
}
